apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: caddy-data-longhorn-pvc
  namespace: caddy
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn
