---
apiVersion: v1
kind: Pod
metadata:
  name: demo-site
  namespace: caddy-web-demo
  labels:
    app: demo-site
spec:
  containers:
    - name: web
      image: nginx:alpine
      resources:
        requests:
          memory: "16Mi"
          cpu: "50m"
        limits:
          memory: "32Mi"
          cpu: "100m"
      volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
  volumes:
    - name: html
      configMap:
        name: demo-html
