apiVersion: v1
kind: Secret
metadata:
  name: auth-oidc-secret
  namespace: homarr
type: Opaque
stringData:
  oidc-client-id: "homarr"
  oidc-client-secret: "oidc-client-secret" # plaintext from: authelia crypto hash generate pbkdf2 ...
---
apiVersion: v1
kind: Secret
metadata:
  name: db-encryption
  namespace: homarr
type: Opaque
stringData:
  db-encryption-key: "db-encryption-key" # plaintext from: openssl rand -base64 32
