---
apiVersion: v1
kind: ConfigMap
metadata:
  name: caddy-config
  namespace: caddy
data:
  Caddyfile: |
    demo.yukselcloud.com {
        reverse_proxy demo-service.caddy-web-demo.svc.cluster.local:80
    }
    pihole.yukselcloud.com {
        reverse_proxy pihole-tcp.pihole.svc.cluster.local:80
    }
