# Caddy Helm values.yaml

replicaCount: 2

image:
  repository: caddy/ingress
  tag: v0.2.1
  pullPolicy: IfNotPresent

ingressController:
  enabled: true

resources:
  limits:
    cpu: 500m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

service:
  type: LoadBalancer
  ports:
    http: 80
    https: 443

nodeSelector:
  role: master-ingress

tolerations: []

affinity: {}

# Optional: persistence config
persistence:
  enabled: false

# Optional: configure liveness/readiness probes
livenessProbe:
  httpGet:
    path: /healthz
    port: 2019
  initialDelaySeconds: 5
  periodSeconds: 10

readinessProbe:
  httpGet:
    path: /healthz
    port: 2019
  initialDelaySeconds: 5
  periodSeconds: 10

# Optional: volume for extra Caddy config (mounted under /etc/caddy)
# Can be used for custom Caddyfile snippets
extraConfig:
  enabled: false
