# ingress:
#   enabled: true
#   hosts:
#     - pihole.lab.local

# will create kubernetes services for web admin
serviceWeb:
  loadBalancerIP: 192.168.0.202
  type: LoadBalancer
  annotations:
    metallb.universe.tf/allow-shared-ip: "pihole-dns"

# will set your admin password for the web inteface
adminPassword: "admin"

# # create a kubernetes service and expose
# # port 53 outside of cluster on the local network
# serviceDns:
#   loadBalancerIP: 192.168.0.202
#   type: LoadBalancer
#   annotations:
#     metallb.universe.tf/allow-shared-ip: "pihole-dns"

serviceDns:
  type: LoadBalancer # give it a MetalLB IP
  loadBalancerIP: 192.168.0.202
  port: 53
  targetPort: 53
  protocol: UDP
  annotations:
    metallb.universe.tf/allow-shared-ip: "pihole-dns"

serviceDnsTCP:
  type: LoadBalancer
  loadBalancerIP: 192.168.0.202
  port: 53
  targetPort: 53
  protocol: TCP
  annotations:
    metallb.universe.tf/allow-shared-ip: "pihole-dns"

# enables cloudflare tunnel sidecar container
# and sets upstream dns in pihole to leverage it
doh:
  enabled: true
  pullPolicy: Always
  envVars: { DOH_UPSTREAM: "https://1.1.1.1/dns-query" }

# pi-hole will automatially create a new
# persistent volume managed by longhorn
# persistentVolumeClaim:
#   enabled: true
#   storageClass: "longhorn"

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 256Mi

# Stick it to your infra node
nodeSelector:
  role: pi-hole

tz: "Europe/Helsinki"
