apiVersion: apps/v1
kind: Deployment
metadata:
  name: caddy-web
  namespace: caddy-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: caddy-web
  template:
    metadata:
      labels:
        app: caddy-web
    spec:
      containers:
        - name: caddy
          image: caddy:2
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
            - containerPort: 443
          volumeMounts:
            - mountPath: /srv
              name: site
            - mountPath: /etc/caddy/Caddyfile
              subPath: Caddyfile
              name: config
      initContainers: # Comment out this block if you don't need to copy HTML files
        - name: copy-html
          image: busybox
          command: ["sh", "-c", "cp /src/index.html /dest/index.html"]
          volumeMounts:
            - name: html-source
              mountPath: /src
            - name: site
              mountPath: /dest
      volumes:
        - name: config
          configMap:
            name: caddy-web-config
        - name: html-source
          configMap:
            name: caddy-html-files
        - name: site
          persistentVolumeClaim:
            claimName: caddy-web-longhorn-pvc
