---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: caddy-web-pv
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: "" # This prevents dynamic provisioning
  hostPath:
    path: /data/caddy-web
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: caddy-web-pvc
  namespace: caddy-web
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: "" # This must match the PV
  volumeName: caddy-web-pv # This forces binding to your specific PV
