apiVersion: v1
kind: Service
metadata:
  name: caddy-web
  namespace: caddy-web
spec:
  selector:
    app: caddy-web
  ports:
    - port: 80
      targetPort: 80
      name: http
    - port: 443
      targetPort: 443
      name: https
  type: LoadBalancer
