---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tailscale-router
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tailscale-router
  template:
    metadata:
      labels:
        app: tailscale-router
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      serviceAccountName: tailscale
      nodeSelector:
        role: master-ingress
      containers:
        - name: tailscale
          image: tailscale/tailscale:latest
          resources:
            requests:
              cpu: 25m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 128Mi
          securityContext:
            capabilities:
              add: ["NET_ADMIN", "SYS_MODULE"]
          env:
            - name: TS_AUTHKEY
              valueFrom:
                secretKeyRef:
                  name: tailscale-auth
                  key: TS_AUTHKEY
            - name: TS_EXTRA_ARGS
              value: >
                --advertise-exit-node
                --advertise-routes=192.168.0.192/27,10.42.0.0/16,10.43.0.0/16
                --hostname=k3s-exit-router
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_UID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.uid
          volumeMounts:
            - name: tailscale-state
              mountPath: /var/lib/tailscale
      volumes:
        - name: tailscale-state
          hostPath:
            path: /var/lib/tailscale
            type: DirectoryOrCreate
