apiVersion: v1
kind: Service
metadata:
  name: beszel
  namespace: monitoring
  labels:
    app: beszel
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.0.225
  selector:
    app: beszel
  ports:
    - name: http
      port: 8090
      targetPort: 8090
      protocol: TCP
