apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Release.Namespace }}
data:
  server.yml: |
    base-url: {{ .Values.config.baseURL }}
    cache-file: /var/cache/ntfy/cache.db
    auth-file: /var/lib/ntfy/auth.db
    auth-default-access: {{ .Values.config.authDefaultAccess }}
    behind-proxy: {{ .Values.config.behindProxy }}
    log-level: {{ .Values.config.logLevel }}
    enable-login: {{ .Values.config.enableLogin }}
    require-login: true
    upstream-base-url: {{ .Values.config.upstreamBaseURL }}
