apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: ntfy
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          args: ["serve"]
          ports:
            - containerPort: 80
          env:
            - name: NTFY_AUTH_USERS
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.auth.existingSecret }}
                  key: auth-users
            - name: NTFY_AUTH_TOKENS
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.auth.existingSecret }}
                  key: auth-tokens
          volumeMounts:
            - name: config
              mountPath: /etc/ntfy/server.yml
              subPath: server.yml
            - name: data
              mountPath: /var/cache/ntfy
              subPath: cache
            - name: data
              mountPath: /var/lib/ntfy
              subPath: auth
          resources:
            requests:
              memory: 64Mi
              cpu: 50m
            limits:
              memory: 128Mi
      volumes:
        - name: config
          configMap:
            name: {{ .Release.Name }}-config
        - name: data
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-data
