apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: db
type: Opaque
stringData:
  mysql-root-password: "MYSQL_ROOT_PASSWORD"
  mysql-replication-password: "MYSQL_REPLICATION_PASSWORD"
  mysql-password: "MYSQL_PASSWORD"
