apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: authelia-config
  namespace: auth
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 500Mi
