#cloud-config
hostname: ${hostname}
users:
  - name: lab
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    groups: users, admin
    lock_passwd: false
    passwd: "password"

ssh_pwauth: true

packages:
  - curl
  - git
  - htop
  - net-tools
  - nfs-common
  - resolvconf
  - vim

runcmd:
  - apt update
  - apt upgrade -y
