apiVersion: apps/v1
kind: Deployment
metadata:
  name: qbittorrent
  namespace: media
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qbittorrent
  template:
    metadata:
      labels:
        app: qbittorrent
    spec:
      containers:
        # ==========================
        # Gluetun VPN + Proxy
        # ==========================
        - name: gluetun
          image: qmcgaw/gluetun:v3.41.0
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
          resources:
            requests:
              cpu: 50m
              memory: 96Mi
            limits:
              cpu: 500m
              memory: 512Mi
          env:
            - name: TZ
              value: Europe/Helsinki
            - name: VPN_SERVICE_PROVIDER
              value: custom
            - name: VPN_TYPE
              value: wireguard
            - name: WIREGUARD_CONF_FILE
              value: wg0.conf
            - name: FIREWALL
              value: "on"
          ports:
            - containerPort: 8080
            - containerPort: 6881
            - containerPort: 6881
              protocol: UDP
          volumeMounts:
            - name: config
              mountPath: /gluetun

        # ==========================
        # qBittorrent
        # ==========================
        - name: qbittorrent
          image: linuxserver/qbittorrent:latest
          resources:
            requests:
              cpu: 50m
              memory: 96Mi
            limits:
              cpu: 1500m
              memory: 1Gi
          env:
            - name: TZ
              value: Europe/Helsinki
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: WEBUI_PORT
              value: "8080"
            - name: DOCKER_MODS
              value: ghcr.io/vuetorrent/vuetorrent-lsio-mod:latest
            - name: WEBUI_ALTERNATIVE
              value: "true" # Set chown -R 1000:1000 vuetorrent for permission fix

          volumeMounts:
            - name: config
              mountPath: /config
            - name: downloads
              mountPath: /downloads
            - name: completed
              mountPath: /completed
            - name: movies
              mountPath: /movies
            - name: tv
              mountPath: /tv

      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: media-qbittorrent-config
        - name: downloads
          persistentVolumeClaim:
            claimName: media-downloads
        - name: completed
          persistentVolumeClaim:
            claimName: media-completed
        - name: movies
          persistentVolumeClaim:
            claimName: media-movies
        - name: tv
          persistentVolumeClaim:
            claimName: media-tv
