apiVersion: v1
kind: Service
metadata:
  name: qbittorrent-proxy
  namespace: media
spec:
  selector:
    app: qbittorrent
  ports:
    - name: http-proxy
      port: 8888
      targetPort: 8888
    - name: socks-proxy
      port: 1080
      targetPort: 1080
  type: ClusterIP
