apiVersion: v1
kind: Service
metadata:
  name: qbittorrent
  namespace: media
spec:
  selector:
    app: qbittorrent
  type: LoadBalancer
  loadBalancerIP: 192.168.0.210
  ports:
    - name: webui
      port: 8080
      targetPort: 8080
    - name: torrent
      port: 6881
      targetPort: 6881
    - name: torrent-udp
      port: 6881
      targetPort: 6881
      protocol: UDP
