---
apiVersion: v1
kind: Service
metadata:
  name: paperless-ngx
  namespace: paperless
spec:
  selector:
    app: paperless-ngx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
