apiVersion: v1
kind: Secret
metadata:
  name: speedtest-db-secret
  namespace: speedtest-tracker
type: Opaque
stringData:
  app-key: "base64:<secret>" # Generate by echo -n 'base64:'; openssl rand -base64 32;
  password: "PASSWORD" # Generate by openssl rand -base64 32
